# Generated by Django 5.1 on 2024-11-10 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('eEmail_personal', models.EmailField(blank=True, max_length=40)),
                ('eEmail_laboral', models.EmailField(blank=True, max_length=40)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('documentType', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('P', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento')),
                ('documentNumber', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=47)),
                ('department', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=40)),
                ('formation', models.CharField(blank=True, max_length=50)),
                ('knowledge', models.CharField(blank=True, max_length=50)),
                ('skill', models.CharField(blank=True, max_length=50)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('numberBank', models.CharField(blank=True, max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
