# Generated by Django 5.1 on 2024-11-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('Ok Web', 'Ok Web'), ('Complemento', 'Complemento'), ('Constructor', 'Constructor'), ('Temas', 'Temas')], default='OK', max_length=12, verbose_name='Categoria del servicio')),
            ],
        ),
    ]
