# Generated by Django 5.1 on 2026-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Ok Web', 'Ok Web'), ('Complemento', 'Complemento'), ('Constructor', 'Constructor'), ('Temas', 'Temas')], default='OK Web', max_length=12, verbose_name='Categoria del servicio'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
