# Generated by Django 5.1 on 2026-08-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_services_updated_at_services_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
