# Generated by Django 5.1 on 2024-11-13 19:38

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('tributare_type_id', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('P', 'Pasaporte'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('NIUP', 'NIUP')], default='CC', max_length=5, verbose_name='Tipo de Identificación Tributaria')),
                ('id_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('position', models.CharField(blank=True, max_length=30)),
                ('photo', models.CharField(blank=True, max_length=40, null=True)),
                ('mark_name', models.CharField(blank=True, max_length=30)),
                ('corporate_name', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=30)),
                ('taxpayer_type', models.CharField(choices=[('Juridico', 'Persona juridica'), ('Natural', 'Persona natural')], default='Natural', max_length=10, verbose_name='Tipo de contribuyente')),
                ('tax_liability', models.CharField(choices=[('IVA', 'IVA impuesto sobre las ventas'), ('INC', 'INC impuesto nacional al consumo'), ('IVA-INC', 'IVA - INC'), ('N/A', 'No aplica')], default='IVA', max_length=8, verbose_name='Responsabilidad tributaria')),
                ('tax_id_type', models.CharField(choices=[('01', 'Gran contribuyente'), ('02', 'Autorretenedor'), ('03', 'Agente de retencion en el impuesto sobre las ventas'), ('04', 'Regimen simple de tributacion'), ('05', 'R-99-PN'), ('06', 'No aplica'), ('07', 'Otros')], default='01', max_length=55, verbose_name='Tipo de identificacion tributaria 2')),
                ('regime_type', models.CharField(choices=[('IVA', 'Responsable de IVA'), ('No IVA', 'Responsable de NO IVA')], default='IVA', max_length=7, verbose_name='Tipo de regimen')),
            ],
        ),
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('paymentMethod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('expirationDate', models.DateField(default=datetime.datetime(2024, 12, 13, 19, 38, 46, 676026, tzinfo=datetime.timezone.utc))),
                ('price', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.services')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contactos', to='Clientes.client')),
            ],
        ),
    ]
