# Generated by Django 5.1 on 2026-07-29 05:08

import Apps.Clientes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TributaryAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('tributary_id', models.CharField(blank=True, max_length=30)),
                ('tributary_number', models.CharField(blank=True, max_length=30)),
                ('taxpayer_type', models.CharField(choices=[('N/A', 'No aplica'), ('Juridico', 'Persona juridica'), ('Natural', 'Persona natural')], default='Natural', max_length=10, verbose_name='Tipo de contribuyente')),
                ('tax_liability', models.CharField(choices=[('IVA', 'IVA impuesto sobre las ventas'), ('INC', 'INC impuesto nacional al consumo'), ('IVA-INC', 'IVA - INC'), ('N/A', 'No aplica')], default='IVA', max_length=8, verbose_name='Responsabilidad tributaria')),
                ('tax_id_type', models.CharField(choices=[('01', 'Gran contribuyente'), ('02', 'Autorretenedor'), ('03', 'Agente de retencion en el impuesto sobre las ventas'), ('04', 'Regimen simple de tributacion'), ('05', 'R-99-PN'), ('06', 'No aplica'), ('07', 'Otros')], default='01', max_length=55, verbose_name='Tipo de identificacion tributaria 2')),
                ('regime_type', models.CharField(choices=[('N/A', 'No aplica'), ('IVA', 'Responsable de IVA'), ('No IVA', 'Responsable de NO IVA')], default='IVA', max_length=7, verbose_name='Tipo de regimen')),
                ('rut', models.FileField(blank=True, null=True, upload_to='Documents/RUT')),
                ('c_commerce', models.FileField(blank=True, null=True, upload_to='Documents/C_Commercial')),
            ],
        ),
        migrations.CreateModel(
            name='UserClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='TaxPayer',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='id_number',
            new_name='documentNumber',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='corporate_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mark_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='position',
        ),
        migrations.RemoveField(
            model_name='client',
            name='regime_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_id_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_liability',
        ),
        migrations.RemoveField(
            model_name='client',
            name='taxpayer_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tributare_type_id',
        ),
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='documentType',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('P', 'Pasaporte'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('NIUP', 'NIUP')], default='CC', max_length=5, verbose_name='Tipo de Identificación'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='currency',
            field=models.CharField(default='COP', max_length=7),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='is_recurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='recurrence',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Anual', 'Anual')], default='Mensual', max_length=8, verbose_name='Recurrencia'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/Clients'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='expirationDate',
            field=models.DateField(default=Apps.Clientes.models.default_expiration_date),
        ),
        migrations.AddField(
            model_name='tributaryadd',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.client'),
        ),
        migrations.AddField(
            model_name='userclientassignment',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, to='Clientes.client'),
        ),
        migrations.AddField(
            model_name='userclientassignment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
