# Generated by Django 5.1 on 2026-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accesos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='img',
        ),
        migrations.AddField(
            model_name='access',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='access',
            name='pin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='access',
            name='type',
            field=models.CharField(choices=[('H', 'Herramienta'), ('S', 'Social'), ('C', 'Complemento'), ('T', 'Temas'), ('O', 'Otros')], default='s', max_length=12, verbose_name='Tipo de Acceso'),
        ),
        migrations.AddField(
            model_name='access',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='access',
            name='url',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='access',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
