# Generated by Django 5.1 on 2026-08-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accesos', '0002_remove_access_img_access_password_access_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
